services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
