services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - app-network
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Cambia el puerto según lo que indique Vite
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
networks:
  app-network:
    driver: bridge
